astring = "Hello world!"
print("single quotes are ' '")

print(len(astring)) # this will give the length of the string
print(astring.index("o")) # this will give the index of first occurrence of o
print(astring.count("o")) # this will gives the number of o's in the string
print(astring[3:7]) # this will give a substring

# This prints the characters of string from 3 to 7 skipping one character. This is extended slice syntax. The general form is [start:stop:step].
print(astring[3:7:2])
print(astring[3:7:1])

# There is no function like strrev in C to reverse a string. But with the above mentioned type of slice syntax you can easily reverse a string like this
print(astring[::-1]) 

print(astring.upper())
print(astring.lower())

print(astring.startswith("Hello"))
print(astring.endswith("asdfasdfasdf"))

afewwords = astring.split(" ") # new list will be generated by spliting by " "
print(afewwords)